### ISSUE TITLE
PRP Code Review 14/10 (Student A only)

### ISSUE THREAD

**Issue by KatIsCoding** [mustabbas/TvMovies#22]
## Hey @mustabbas, your work on your project is actually pretty good! We are searching for new ways of making your project even better, however, I still think your project is awesome!!

**Comment by ramiaquista** [comment]
## Awesome Job 💯

- I would recommend changing the text of Comment Btn, what I would put is Comments instead of comments. Basically just applying Capital letter to C. 
- Another change I would recommend is to add some `padding-bottom` to last row cards because the footer overlaps it.

### You have done an amazing job, keep coding and enjoying the journey 😄
